services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: ${CLOUDFLARED_CONTAINER_NAME}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: ${COMMAND}
    networks:
      - cloudflared-net
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}

networks:
  cloudflared-net:
    external: true
